_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: SecZetta Integration
features:
  bot_user:
    display_name: SecZetta Bot
    always_online: false
oauth_config:
  scopes:
    bot:
      - chat:write.customize
      - chat:write.public
      - chat:write
      - users:read.email
      - users:read
      - users.profile:read
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
